import { Cluster, DashboardStats, DefectType, Detection, POI, RoadHierarchy, Severity } from '@/types/vigilance';

export const CHENNAI_CENTER: [number, number] = [80.2030, 13.0067]; // [lon, lat] - Guindy / Kathipara
export const DEFAULT_ZOOM = 11.5;
export const DEFAULT_PITCH = 30;

export const CARTO_DARK_TILES = [
  'https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png',
  'https://b.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png',
  'https://c.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}@2x.png',
];

export const DEFECT_INFO: Record<DefectType, { name: string; color: string; desc: string; badgeBg: string }> = {
  D00: {
    name: 'Longitudinal Crack',
    color: '#3B82F6',
    badgeBg: 'bg-blue-950/80 text-blue-300 border-blue-800',
    desc: 'Cracks parallel to road direction',
  },
  D10: {
    name: 'Transverse Crack',
    color: '#F59E0B',
    badgeBg: 'bg-amber-950/80 text-amber-300 border-amber-800',
    desc: 'Cracks perpendicular to road direction',
  },
  D20: {
    name: 'Alligator Crack',
    color: '#F97316',
    badgeBg: 'bg-orange-950/80 text-orange-300 border-orange-800',
    desc: 'Interconnected crack mesh pattern',
  },
  D40: {
    name: 'Pothole',
    color: '#EF4444',
    badgeBg: 'bg-red-950/80 text-red-300 border-red-800',
    desc: 'Bowl-shaped structural road depression',
  },
};

export const SEVERITY_CONFIG: Record<Severity, { label: string; color: string; bg: string; border: string; glow: string }> = {
  critical: {
    label: 'Critical',
    color: '#EF4444',
    bg: 'bg-red-950/70 text-red-400',
    border: 'border-red-800/80',
    glow: 'shadow-[0_0_12px_rgba(239,68,68,0.4)]',
  },
  high: {
    label: 'High',
    color: '#F97316',
    bg: 'bg-orange-950/70 text-orange-400',
    border: 'border-orange-800/80',
    glow: 'shadow-[0_0_12px_rgba(249,115,22,0.4)]',
  },
  medium: {
    label: 'Medium',
    color: '#F59E0B',
    bg: 'bg-amber-950/70 text-amber-400',
    border: 'border-amber-800/80',
    glow: 'shadow-[0_0_10px_rgba(245,158,11,0.3)]',
  },
  low: {
    label: 'Low',
    color: '#22C55E',
    bg: 'bg-emerald-950/70 text-emerald-400',
    border: 'border-emerald-800/80',
    glow: 'shadow-[0_0_10px_rgba(34,197,94,0.3)]',
  },
};

export const CHENNAI_POIS: POI[] = [
  { name: 'SRM Medical College Hospital, Potheri', lat: 12.8233, lon: 80.0440, type: 'hospital' },
  { name: 'MIOT International Hospital', lat: 13.0105, lon: 80.1720, type: 'hospital' },
  { name: 'Apollo Hospital, Greams Road', lat: 13.0619, lon: 80.2522, type: 'hospital' },
  { name: 'Rajiv Gandhi Govt. General Hospital', lat: 13.0785, lon: 80.2765, type: 'hospital' },
  { name: 'Fortis Malar Hospital, Adyar', lat: 13.0063, lon: 80.2575, type: 'hospital' },
  { name: 'Chettinad Super Speciality Hospital', lat: 12.8242, lon: 80.2225, type: 'hospital' },
  { name: 'Anna University Main Campus', lat: 13.0108, lon: 80.2354, type: 'school' },
  { name: 'SRM Institute of Science and Technology', lat: 12.8231, lon: 80.0442, type: 'school' },
  { name: 'IIT Madras', lat: 12.9916, lon: 80.2336, type: 'school' },
  { name: 'Madras Medical College', lat: 13.0802, lon: 80.2783, type: 'school' },
  { name: 'Kendriya Vidyalaya, CLRI Adyar', lat: 13.0012, lon: 80.2565, type: 'school' },
  { name: 'D.A.V. Senior Secondary School, Mogappair', lat: 13.0895, lon: 80.1732, type: 'school' },
];

export const CHENNAI_ROADS: RoadHierarchy[] = [
  { road: 'GST Road (NH-32)', weight: 1.00, significance: 'National Highway corridor connecting airport & southern hubs' },
  { road: 'Kathipara Cloverleaf Junction', weight: 0.90, significance: 'Largest grade-separated interchange in Asia' },
  { road: 'Anna Salai (Mount Road)', weight: 0.85, significance: 'Primary arterial CBD commercial corridor' },
  { road: 'Old Mahabalipuram Road (OMR)', weight: 0.80, significance: 'Expressway IT Corridor connecting tech parks' },
  { road: 'T. Nagar Usman Road', weight: 0.70, significance: 'High-density commercial transit district' },
  { road: 'Velachery Main Road', weight: 0.65, significance: 'High-traffic southern suburban residential arterial' },
  { road: 'Poonamallee High Road', weight: 0.75, significance: 'Western radial arterial artery' },
  { road: 'Anna Nagar 2nd Avenue', weight: 0.60, significance: 'Planned residential arterial corridor' },
];

export const INITIAL_CLUSTERS: Cluster[] = [
  {
    id: 1,
    centroid_lat: 12.9516,
    centroid_lon: 80.1462,
    detection_count: 7,
    dominant_type: 'D40 (Pothole)',
    max_severity: 'critical',
    rpi_score: 94.5,
    status: 'open',
    road_name: 'GST Road, Tambaram (NH-32)',
    contractor_name: 'L&T Highways Infra Ltd',
    contractor_contact: '+91 98401 22345',
    sla_hours: 24,
    nearest_poi: 'MIOT Hospital Corridor',
    poi_distance_m: 420,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 2,
    centroid_lat: 13.0067,
    centroid_lon: 80.2030,
    detection_count: 5,
    dominant_type: 'D40 (Pothole)',
    max_severity: 'critical',
    rpi_score: 89.2,
    status: 'assigned',
    road_name: 'Guindy Kathipara Grade Junction',
    contractor_name: 'NHAI Metro Division Chennai',
    contractor_contact: '+91 91760 55667',
    sla_hours: 12,
    nearest_poi: 'Anna University',
    poi_distance_m: 850,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 3,
    centroid_lat: 13.0604,
    centroid_lon: 80.2496,
    detection_count: 4,
    dominant_type: 'D20 (Alligator Crack)',
    max_severity: 'high',
    rpi_score: 82.1,
    status: 'open',
    road_name: 'Anna Salai (Mount Road)',
    contractor_name: 'GMR Urban Highways Ltd',
    contractor_contact: '+91 98840 77890',
    sla_hours: 24,
    nearest_poi: 'Apollo Hospital, Greams Rd',
    poi_distance_m: 310,
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 4,
    centroid_lat: 12.8231,
    centroid_lon: 80.0442,
    detection_count: 6,
    dominant_type: 'D40 (Pothole)',
    max_severity: 'critical',
    rpi_score: 88.0,
    status: 'open',
    road_name: 'SRM Institute / Potheri Highway',
    contractor_name: 'Chettinad Road Infra Pvt Ltd',
    contractor_contact: '+91 97900 88990',
    sla_hours: 24,
    nearest_poi: 'SRM Medical College',
    poi_distance_m: 180,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 2400000).toISOString(),
  },
  {
    id: 5,
    centroid_lat: 12.9719,
    centroid_lon: 80.2500,
    detection_count: 3,
    dominant_type: 'D10 (Transverse Crack)',
    max_severity: 'high',
    rpi_score: 74.5,
    status: 'assigned',
    road_name: 'Old Mahabalipuram Road (OMR)',
    contractor_name: 'Tamil Nadu Road Dev Corp (TNRDC)',
    contractor_contact: '+91 99400 33445',
    sla_hours: 48,
    nearest_poi: 'IIT Madras Zone',
    poi_distance_m: 1200,
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 6,
    centroid_lat: 13.0827,
    centroid_lon: 80.2707,
    detection_count: 4,
    dominant_type: 'D00 (Longitudinal Crack)',
    max_severity: 'medium',
    rpi_score: 68.4,
    status: 'resolved',
    road_name: 'Poonamallee High Road',
    contractor_name: 'Tamil Nadu PWD Division 4',
    contractor_contact: '+91 94440 11223',
    sla_hours: 48,
    nearest_poi: 'Madras Medical College',
    poi_distance_m: 650,
    created_at: new Date(Date.now() - 21600000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 7,
    centroid_lat: 12.9815,
    centroid_lon: 80.2180,
    detection_count: 3,
    dominant_type: 'D40 (Pothole)',
    max_severity: 'high',
    rpi_score: 79.8,
    status: 'open',
    road_name: 'Velachery Main Road',
    contractor_name: 'Chennai Corp Zone 13 (Adyar)',
    contractor_contact: '+91 94451 90013',
    sla_hours: 72,
    nearest_poi: 'Fortis Malar Hospital',
    poi_distance_m: 1400,
    created_at: new Date(Date.now() - 25200000).toISOString(),
    updated_at: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 8,
    centroid_lat: 13.0418,
    centroid_lon: 80.2341,
    detection_count: 5,
    dominant_type: 'D20 (Alligator Crack)',
    max_severity: 'high',
    rpi_score: 76.2,
    status: 'open',
    road_name: 'T. Nagar Usman Road Commercial',
    contractor_name: 'Chennai Corp Zone 10 (T.Nagar)',
    contractor_contact: '+91 94451 90010',
    sla_hours: 48,
    nearest_poi: 'D.A.V. School Link',
    poi_distance_m: 920,
    created_at: new Date(Date.now() - 28800000).toISOString(),
    updated_at: new Date(Date.now() - 4200000).toISOString(),
  },
  {
    id: 9,
    centroid_lat: 13.0878,
    centroid_lon: 80.2155,
    detection_count: 2,
    dominant_type: 'D00 (Longitudinal Crack)',
    max_severity: 'low',
    rpi_score: 52.0,
    status: 'resolved',
    road_name: 'Anna Nagar 2nd Avenue',
    contractor_name: 'Chennai Corp Zone 8 (Anna Nagar)',
    contractor_contact: '+91 94451 90008',
    sla_hours: 72,
    nearest_poi: 'Kendriya Vidyalaya',
    poi_distance_m: 1600,
    created_at: new Date(Date.now() - 32400000).toISOString(),
    updated_at: new Date(Date.now() - 10800000).toISOString(),
  },
];

export const INITIAL_DETECTIONS: Detection[] = [
  {
    id: 101,
    defect_type: 'D40',
    confidence: 0.94,
    severity: 'critical',
    vehicle_id: 'BUS-TN01-1042',
    road_name: 'GST Road, Tambaram (NH-32)',
    lat: 12.9516,
    lon: 80.1462,
    cluster_id: 1,
    timestamp: new Date(Date.now() - 120000).toISOString(),
    thumbnail_b64: null,
  },
  {
    id: 102,
    defect_type: 'D20',
    confidence: 0.88,
    severity: 'high',
    vehicle_id: 'BUS-TN02-3891',
    road_name: 'Guindy Kathipara Grade Junction',
    lat: 13.0067,
    lon: 80.2030,
    cluster_id: 2,
    timestamp: new Date(Date.now() - 240000).toISOString(),
    thumbnail_b64: null,
  },
  {
    id: 103,
    defect_type: 'D40',
    confidence: 0.96,
    severity: 'critical',
    vehicle_id: 'MUNICIPAL-TRUCK-07',
    road_name: 'SRM Institute / Potheri Highway',
    lat: 12.8231,
    lon: 80.0442,
    cluster_id: 4,
    timestamp: new Date(Date.now() - 360000).toISOString(),
    thumbnail_b64: null,
  },
  {
    id: 104,
    defect_type: 'D10',
    confidence: 0.82,
    severity: 'high',
    vehicle_id: 'PATROL-VAN-12',
    road_name: 'Anna Salai (Mount Road)',
    lat: 13.0604,
    lon: 80.2496,
    cluster_id: 3,
    timestamp: new Date(Date.now() - 480000).toISOString(),
    thumbnail_b64: null,
  },
  {
    id: 105,
    defect_type: 'D00',
    confidence: 0.79,
    severity: 'medium',
    vehicle_id: 'BUS-TN22-5501',
    road_name: 'Old Mahabalipuram Road (OMR)',
    lat: 12.9719,
    lon: 80.2500,
    cluster_id: 5,
    timestamp: new Date(Date.now() - 600000).toISOString(),
    thumbnail_b64: null,
  },
];

export const INITIAL_STATS: DashboardStats = {
  total_detections: 64,
  deduplicated_clusters: 9,
  potholes: 24,
  cracks: 40,
  critical_severity: 14,
  high_severity: 28,
  active_vehicles: 5,
};
